-- 001_init: wallets, transfers, double-entry ledger, treasury seed.
--
-- Correctness rests on the constraints declared here rather than on
-- application logic.

CREATE TABLE wallets (
  user_id       TEXT        PRIMARY KEY,
  -- Backstop to the conditional debit, independent of it: if that debit were
  -- ever wrong the transaction aborts instead of committing negative money.
  -- Named so the application can recognise this specific violation.
  balance_paise BIGINT      NOT NULL DEFAULT 0
                            CONSTRAINT wallets_balance_non_negative
                            CHECK (balance_paise >= 0),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE transfers (
  -- Generated by the application, not the database: the transfer path compares
  -- its own UUID against what ON CONFLICT ... RETURNING gives back, and a
  -- different id means this request lost the race or is a replay.
  id                 UUID        PRIMARY KEY,
  from_user          TEXT        NOT NULL,
  to_user            TEXT        NOT NULL,
  amount_paise       BIGINT      NOT NULL
                                 CONSTRAINT transfers_amount_positive
                                 CHECK (amount_paise > 0),
  idempotency_key    TEXT        NOT NULL,
  -- sha256 of the canonicalised {to_user, amount_paise}, compared on replay to
  -- tell an honest retry from the same key reused for a different intent.
  request_hash       TEXT        NOT NULL,
  -- 'pending' exists only inside an open transaction; a crash rolls it back.
  -- 'applied' and 'rejected' are both terminal and both durable.
  status             TEXT        NOT NULL
                                 CHECK (status IN ('pending', 'applied', 'rejected')),
  reason             TEXT,
  from_balance_after BIGINT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Exactly-once as a database property. Scoped per sender, so one user cannot
  -- deny service to another by guessing keys.
  CONSTRAINT transfers_idem_uniq UNIQUE (from_user, idempotency_key),

  CONSTRAINT transfers_no_self   CHECK (from_user <> to_user),

  CONSTRAINT transfers_reason_iff_rejected
    CHECK ((status = 'rejected') = (reason IS NOT NULL))
);

-- Two rows per applied transfer, summing to zero, so SUM over the table is
-- always zero -- the conservation invariant exposed at GET /invariants.
CREATE TABLE ledger_entries (
  id           BIGSERIAL   PRIMARY KEY,
  transfer_id  UUID        NOT NULL REFERENCES transfers (id),
  user_id      TEXT        NOT NULL REFERENCES wallets (user_id),
  amount_paise BIGINT      NOT NULL,  -- signed; negative is a debit
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Makes double-application physically impossible.
CREATE UNIQUE INDEX ledger_transfer_user_uniq ON ledger_entries (transfer_id, user_id);

CREATE INDEX ledger_user_idx ON ledger_entries (user_id);

-- transfers_idem_uniq already indexes from_user as its leading column.
CREATE INDEX transfers_to_user_idx ON transfers (to_user);

-- The only source of money. Everything reaches a user wallet by moving out of
-- here along the normal transfer path, so SUM(balance_paise) across all wallets
-- is constant for the life of the database. '@treasury' is outside the user_id
-- grammar, so no well-formed request can name this account.
INSERT INTO wallets (user_id, balance_paise)
VALUES ('@treasury', 100000000000000);
