-- ---------------------------------------------------------------------------
-- 001_init: wallets, transfers, double-entry ledger, treasury seed.
--
-- The correctness of this service rests on four constraints declared here
-- rather than on application logic. Each is annotated below.
-- ---------------------------------------------------------------------------

CREATE TABLE wallets (
  user_id       TEXT        PRIMARY KEY,
  -- A database-level backstop against overdraft, independent of the
  -- conditional UPDATE in the transfer path. If that check were ever wrong,
  -- the transaction aborts instead of committing negative money.
  -- Named explicitly so the application can recognise this specific violation
  -- and treat it as the invariant breach it would be.
  balance_paise BIGINT      NOT NULL DEFAULT 0
                            CONSTRAINT wallets_balance_non_negative
                            CHECK (balance_paise >= 0),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE transfers (
  -- Generated by the application, not the database. The transfer path inserts
  -- its own UUID and compares it against what ON CONFLICT ... RETURNING gives
  -- back: a different id means this request lost the race or is a replay.
  id                 UUID        PRIMARY KEY,
  from_user          TEXT        NOT NULL,
  to_user            TEXT        NOT NULL,
  amount_paise       BIGINT      NOT NULL
                                 CONSTRAINT transfers_amount_positive
                                 CHECK (amount_paise > 0),
  idempotency_key    TEXT        NOT NULL,
  -- sha256 of the canonicalised {to_user, amount_paise}. Compared on replay to
  -- distinguish an honest retry from the same key reused for a different
  -- intent (which is a 409).
  request_hash       TEXT        NOT NULL,
  -- 'pending' exists only inside an open transaction; a crash rolls it back.
  -- 'applied' and 'rejected' are both terminal and both durable.
  status             TEXT        NOT NULL
                                 CHECK (status IN ('pending', 'applied', 'rejected')),
  reason             TEXT,
  from_balance_after BIGINT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Exactly-once becomes a database property rather than application logic.
  -- Scoped per sender, so one user cannot deny service to another (or probe
  -- their history) by guessing keys.
  CONSTRAINT transfers_idem_uniq UNIQUE (from_user, idempotency_key),

  -- Self-transfer is unrepresentable, not merely validated at the edge.
  CONSTRAINT transfers_no_self   CHECK (from_user <> to_user),

  -- A reason is recorded if and only if the transfer was rejected.
  CONSTRAINT transfers_reason_iff_rejected
    CHECK ((status = 'rejected') = (reason IS NOT NULL))
);

-- Double-entry: every applied transfer writes exactly two rows that sum to
-- zero. SUM(amount_paise) over the whole table is therefore always 0, which is
-- the conservation invariant exposed at GET /invariants.
CREATE TABLE ledger_entries (
  id           BIGSERIAL   PRIMARY KEY,
  transfer_id  UUID        NOT NULL REFERENCES transfers (id),
  user_id      TEXT        NOT NULL REFERENCES wallets (user_id),
  amount_paise BIGINT      NOT NULL,  -- signed; negative is a debit
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Makes double-application physically impossible: a second attempt to post the
-- same transfer for the same user violates this index and aborts.
CREATE UNIQUE INDEX ledger_transfer_user_uniq
  ON ledger_entries (transfer_id, user_id);

CREATE INDEX ledger_user_idx ON ledger_entries (user_id);

-- Participant lookups for GET /transfers/:id are by primary key, but listing a
-- counterparty's transfers scans by to_user. transfers_idem_uniq already
-- indexes from_user as its leading column.
CREATE INDEX transfers_to_user_idx ON transfers (to_user);

-- ---------------------------------------------------------------------------
-- The treasury: the single source of all money in the system.
--
-- Money enters a user wallet only by moving out of here, along the same
-- transaction path as any other transfer. SUM(balance_paise) across all
-- wallets is therefore constant forever, which is what makes conservation an
-- assertion a reviewer can check rather than a claim they must trust.
--
-- '@treasury' is outside the user_id grammar, so no well-formed request can
-- name this account.
-- ---------------------------------------------------------------------------
INSERT INTO wallets (user_id, balance_paise)
VALUES ('@treasury', 100000000000000);
